<?php

namespace AngryChimps\ApiBundle\Controller;

use AngryChimps\ApiBundle\Services\LocationService;
use AngryChimps\ApiBundle\Services\ResponseService;
use AngryChimps\ApiBundle\Services\SessionService;
use Norm\riak\Company;
use Norm\riak\Location;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\Route;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\Template;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\Method;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\RequestStack;

/**
 * Class LocationController
 * @package AngryChimps\ApiBundle\Controller
 *
 * @Route("/location")
 */
class LocationController extends AbstractController
{
    /** @var  LocationService */
    protected $locationService;

    public function __construct(RequestStack $requestStack, SessionService $sessionService,
                                ResponseService $responseService, LocationService $locationService)
    {
        $this->locationService = $locationService;
        parent::__construct($requestStack, $sessionService, $responseService); // TODO: Change the autogenerated stub
    }


    /**
     * @Route("/{id}")
     * @Method({"GET"})
     */
    public function indexGetAction($id)
    {
        $location = Location::getByPk($id);

        if($location === null) {
            $errors = array(
                'human' => 'Unable to find a location with that id',
                'code' => 'Api.LocationController.indexGetAction.1'
            );
            return $this->responseService->failure(404, $errors);
        }

        $company = Company::getByPk($location->companyId);

        if($company === null) {
            $errors = array(
                'human' => 'Unable to find a company which corresponds to that location',
                'code' => 'Api.LocationController.indexGetAction.2'
            );
            return $this->responseService->failure(400, $errors);
        }

        $user = $this->getAuthenticatedUser();
        if($user !== null && in_array($user->id, $company->administerMemberIds)) {
            return $this->responseService->success(array('location' => $location->getPrivateArray()));
        }
        else {
            return $this->responseService->success(array('location' => $location->getPublicArray()));
        }
    }

    /**
     * @Route("/")
     * @Method({"POST"})
     */
    public function indexPostAction()
    {
        $payload = $this->getPayload();
        $name = $payload['name'];
        $companyId = $payload['company_id'];
        $street1 = $payload['street1'];
        $street2 = $payload['street2'];
        $zip = $payload['zip'];
        $phone = $payload['phone'];

        $company = Company::getByPk($companyId);

        if($company === null) {
            $errors = array(
                'human' => 'Unable to find a company  with that id',
                'code' => 'Api.LocationController.indexPostAction.1'
            );
            return $this->responseService->failure(404, $errors);
        }

        $errors = array();
        $location = $this->locationService->createLocation($name, $street1, $street2, $zip, $phone, $company, $this->user, $errors);
        if($location === false) {
            $errors = array(
                'human' => 'Error validating location fields',
                'code' => 'Api.LocationController.indexPostAction.1'
            );
            return $this->responseService->failure(400, $errors);
        }

        return $this->responseService->success(array('company' => $location->getPrivateArray()));
    }

    /**
     * @Route("/{id}")
     * @Method({"PUT"})
     */
    public function indexPutAction($id)
    {
        $location = Location::getByPk($id);

        if($location === null) {
            $errors = array(
                'human' => 'Unable to find a location with that id',
                'code' => 'Api.LocationController.indexPutAction.1'
            );
            return $this->responseService->failure(404, $errors);
        }

        $company = Company::getByPk($location->companyId);

        if($company === null) {
            $errors = array(
                'human' => 'Unable to find a company which corresponds to that location',
                'code' => 'Api.LocationController.indexPutAction.2'
            );
            return $this->responseService->failure(400, $errors);
        }

        if(!$this->isAuthorizedSelf($company->administerMemberIds)) {
            $errors = array(
                'human' => 'This user is not authorized to perform this action',
                'code' => 'Api.LocationController.indexPutAction.3'
            );
            return $this->responseService->failure(401, $errors);
        }

        $payload = $this->getPayload();
        $name = $payload['name'];
        $street1 = $payload['street1'];
        $street2 = $payload['street2'];
        $zip = $payload['zip'];
        $phone = $payload['phone'];

        $errors = array();
        $company = $this->locationService->updateLocation($location, $company, $name, $street1, $street2, $zip, $phone, $errors);
        if($company === false) {
            $errors = array(
                'human' => 'Unable to validate location inputs',
                'code' => 'Api.LocationController.indexPutAction.4',
            );
            return $this->responseService->failure(400, $errors);
        }

        return $this->responseService->success(array('company' => $company));
    }

    /**
     * @Route("/{id}")
     * @Method({"DELETE"})
     */
    public function indexDeleteAction($id)
    {
        $location = Location::getByPk($id);

        if($location === null) {
            $errors = array(
                'human' => 'Unable to find a location with that id',
                'code' => 'Api.LocationController.indexDeleteAction.1'
            );
            return $this->responseService->failure(404, $errors);
        }

        $company = Company::getByPk($location->companyId);

        if($company === null) {
            $errors = array(
                'human' => 'Unable to find a company which corresponds to that location',
                'code' => 'Api.LocationController.indexDeleteAction.2'
            );
            return $this->responseService->failure(400, $errors);
        }

        if(!$this->isAuthorizedSelf($company->administerMemberIds)) {
            $errors = array(
                'human' => 'This user is not authorized to perform this action',
                'code' => 'Api.LocationController.indexDeleteAction.3'
            );
            return $this->responseService->failure(401, $errors);
        }

        $location->status = Location::DISABLED_STATUS;
        $location->save();

        return $this->responseService->success();
    }

}
