parameters:
    amazon_s3.key: AKIAIOO2VYJTIR4BS77A
    amazon_s3.secret: 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
    amazon_s3.region: us-east-1
    angry_chimps_media.controller.default.class: AngryChimps\MediaBundle\Controller\DefaultController

services:
#    angry_chimps_media.example:
#        class: AngryChimps\MediaBundle\Example
#        arguments: [@service_id, "plain_value", %parameter%]
    angry_chimps_media.media:
        class: AngryChimps\MediaBundle\Services\MediaService
        arguments: ["%kernel.environment%", "@knp_gaufrette.filesystem_map", "%angry_chimps_media.filesystem_info%"]

    angry_chimps_media.aws_s3.client:
        class: Aws\S3\S3Client
        factory_class: Aws\S3\S3Client
        factory_method: 'factory'
        arguments:
            -
                key: %amazon_s3.key%
                secret: %amazon_s3.secret%
                region: %amazon_s3.region%

    ##############################################################
    ###                  Controllers                           ###
    ##############################################################
    angry_chimps_media.default.controller:
            class:     "%angry_chimps_media.controller.default.class%"
            arguments: ["@request_stack", "@angry_chimps_media.media"]
