angry_chimps_sample_generate:
    path:     /generate/{folderToProcess}/{fileToProcess}
    methods: ["GET"]
    defaults:
        _controller: angry_chimps_sample.default.controller:generateAction
        folderToProcess: ~
        fileToProcess: ~

angry_chimps_sample_reset:
    path:     /reset/{folderToProcess}/{fileToProcess}
    methods: ["GET"]
    defaults:
        _controller: angry_chimps_sample.default.controller:resetAction
        folderToProcess: ~
        fileToProcess: ~
