realms:
    riak:
        namespace: "Norm\\riak"
        primary_datastore: "riak_ds"
        cache_datastore: null
    mysql:
        namespace: "Norm\\mysql"
        primary_datastore: "mysql_ds"
        cache_datastore: null
    es:
        namespace: "Norm\\es"
        primary_datastore: "es_ds"
        cache_datastore: null
