debug: true
datastores:
    riak_ds:
        driver: "riak_blob"
        host: "localhost"
        port: 8087
    mysql_ds:
        driver: "mysql"
        db_name: "ac"
        host: "localhost"
        port: 3306
        user: "root"
        password: ""
    es_ds:
        driver: "elasticsearch"
        index_name: ac
        nodes:
            - node1:
                host: "localhost"
                port: 9200
