datastores:
    riak_ds:
        driver: "riak_blob"
        host: "localhost"
        port: 8087
    mysql_ds:
        driver: "mysql"
        db_name: "ac"
        host: "acdb.ckqkc6zyc9bn.us-east-1.rds.amazonaws.com"
        port: 3306
        user: "root"
        password: "zBkt4oHIcFci"
