imports:
    - { resource: config_dev.yml }

framework:
    test: ~
    session:
        storage_id: session.storage.mock_file
    profiler:
        collect: false

web_profiler:
    toolbar: false
    intercept_redirects: false

swiftmailer:
    disable_delivery: true

#armetiz_facebook:
#    enabled: true
#    sdk:
#        ac_login:
#            app_id: 378121139011542
#            secret: 0fefe9a9e1a36abc6db65dedafd30736
#            enabled: true
#            default: true

angry_chimps_api:
    debug: true
    base_url: http://devvy.angrychimps.com/api/v1

angry_chimps_sample:
    base_url: http://loco.angrychimps.com/api/v1

ac_norm:
    debug: true
    datastores:
        riak_ds:
            driver: "riak_blob"
            host: "localhost"
            port: 8087
        mysql_ds:
            driver: "mysql"
            db_name: "ac"
            host: "localhost"
            port: 3306
            user: "root"
            password: ""
        es_ds:
            driver: "elasticsearch"
            index_name: ac
            servers:
                - host: "localhost"
                  port: 9200
