imports:
    - { resource: parameters.yml }
    - { resource: security.yml }
#    - { resource: "../../src/AngryChimps/NormBundle/realms/Norm/riak/validations/validations.yml" }
#    - { resource: "@AngryChimpsSecurityBundle/Resources/config/services.yml" }

framework:
    #esi:             ~
    #translator:      { fallback: "%locale%" }
    secret:          "%secret%"
    router:
        resource: "%kernel.root_dir%/config/routing.yml"
        strict_requirements: ~
    form:            ~
#    csrf_protection: ~
    validation:      { enable_annotations: false, enabled: true }
    templating:
        engines: ['twig']
        #assets_version: SomeVersionScheme
    default_locale:  "%locale%"
    trusted_hosts:   ~
    trusted_proxies: ~
    session:
        # handler_id set to null will use default session handler from php.ini
        handler_id:  ~
    fragments:       ~
    http_method_override: true

# Twig Configuration
twig:
    debug:            "%kernel.debug%"
    strict_variables: "%kernel.debug%"
#    exception_controller: 'FOS\RestBundle\Controller\ExceptionController::showAction'

# Assetic Configuration
assetic:
    debug:          "%kernel.debug%"
    use_controller: false
    bundles:        [ ]
    #java: /usr/bin/java
    filters:
        cssrewrite: ~
        #closure:
        #    jar: "%kernel.root_dir%/Resources/java/compiler.jar"
        #yui_css:
        #    jar: "%kernel.root_dir%/Resources/java/yuicompressor-2.4.7.jar"

# Doctrine Configuration
#doctrine:
#    dbal:
#        driver:   "%database_driver%"
#        host:     "%database_host%"
#        port:     "%database_port%"
#        dbname:   "%database_name%"
#        user:     "%database_user%"
#        password: "%database_password%"
#        charset:  UTF8
#        # if using pdo_sqlite as your database driver, add the path in parameters.yml
#        # e.g. database_path: "%kernel.root_dir%/data/data.db3"
#        # path:     "%database_path%"
#
#    orm:
#        auto_generate_proxy_classes: "%kernel.debug%"
#        auto_mapping: true

# Angry Chimps Mailer Configuration
angry_chimps_mailer:
    from:   "donotreply@angrychimps.com"

# Swiftmailer Configuration
swiftmailer:
    transport: "%mailer_transport%"
    host:      "%mailer_host%"
    username:  "%mailer_user%"
    password:  "%mailer_password%"
    spool:     { type: memory }

fos_rest:
    view:
        formats:
            json: true
        mime_types:
            json: ['application/json', 'application/x-json', 'application/vnd.example-com.foo+json']
    routing_loader:
        default_format: json

angry_chimps_geo:
    google_api_key: AIzaSyArupKalnQR4uprl9raMJwXSwunIHWl41o
    google_maps_api_address: https://maps.googleapis.com/maps/api/geocode/json
    google_maps_time_address: https://maps.googleapis.com/maps/api/timezone/json

angry_chimps_api:
    session_header_name: angrychimps-api-session-token

angry_chimps_sample:
    session_header_name: angrychimps-api-session-token


ac_norm:
    namespace: Norm

knp_gaufrette:
    adapters:
        member_images:
            aws_s3:
                service_id: 'angry_chimps_media.aws_s3.client'
                bucket_name: 'angrychimps-member-images'
                options:
                    directory: %kernel.environment%
        company_images:
            aws_s3:
                service_id: 'angry_chimps_media.aws_s3.client'
                bucket_name: 'angrychimps-company-images'
                options:
                    directory: %kernel.environment%
    filesystems:
        member_images_fs:
            adapter:    member_images
        company_images_fs:
            adapter:    company_images

angry_chimps_media:
    filesystems:
        member_images_fs:
            upload_width_px: 480
            upload_height_px: 480
        company_images_fs:
            upload_width_px: 700
            upload_height_px: 480
