imports:
    - { resource: config.yml }


#framework:
#    validation:
#        cache: apc

#doctrine:
#    orm:
#        metadata_cache_driver: apc
#        result_cache_driver: apc
#        query_cache_driver: apc

monolog:
    handlers:
        main:
            type:         fingers_crossed
            action_level: error
            handler:      nested
        nested:
            type:  stream
            path:  "%kernel.logs_dir%/%kernel.environment%.log"
            level: debug
        console:
            type:  console

swiftmailer:
    disable_delivery: false

angry_chimps_api:
    debug: false
    base_url: http://proddy.angrychimps.com/api/v1

angry_chimps_sample:
    base_url: http://loco.angrychimps.com/api/v1

ac_norm:
    debug: true
    datastores:
        riak_ds:
            driver: "riak_blob"
            servers:
              -
                host: "localhost"
                port: 8087
            prefix: __norm_classmaps_prod_
        mysql_ds:
            driver: "mysql"
            db_name: "ac"
            host: "acdb.ckqkc6zyc9bn.us-east-1.rds.amazonaws.com"
            port: 3306
            user: "root"
            password: "zBkt4oHIcFci"
        es_ds:
            driver: "elasticsearch"
            index_name: ac
            default_analyzer: english
            shards: 4
            replicas: 1
            servers:
                - host: "localhost"
                  port: 9200
