imports:
    - { resource: config.yml }


framework:
    router:
        resource: "%kernel.root_dir%/config/routing_dev.yml"
        strict_requirements: true
    profiler: { only_exceptions: false }

web_profiler:
    toolbar: "%debug_toolbar%"
    intercept_redirects: "%debug_redirects%"

monolog:
    handlers:
        main:
            type:   stream
            path:   "%kernel.logs_dir%/%kernel.environment%.log"
            level:  debug
        console:
            type:   console
            bubble: false
        # uncomment to get logging in your browser
        # you may have to allow bigger header sizes in your Web server configuration
        #firephp:
        #    type:   firephp
        #    level:  info
        #chromephp:
        #    type:   chromephp
        #    level:  info

assetic:
    use_controller: "%use_assetic_controller%"

#swiftmailer:
#    delivery_address: me@example.com

#armetiz_facebook:
#    enabled: true
#    sdk:
#        ac_login:
#            app_id: 378121139011542
#            secret: 0fefe9a9e1a36abc6db65dedafd30736
#            enabled: true
#            default: true

angry_chimps_api:
    debug: true
    base_url: http://devvy3.angrychimps.com/api/v1

angry_chimps_sample:
    base_url: http://devvy3.angrychimps.com/api/v1


ac_norm:
    debug: true
    datastores:
        riak_ds:
            driver: riak2
            servers:
              -
                host: "127.0.0.1"
                port: 8087
                http_port: 8098
            prefix: __norm_dev_1_
        es_ds:
            driver: "elasticsearch"
            index_name: ac_dev_1
            default_analyzer: english
            shards: 4
            replicas: 1
            servers:
                - host: "localhost"
                  port: 9200
