angry_chimps_admin:
    resource: "@AngryChimpsAdminBundle/Resources/config/routing.yml"
    prefix:   /admin

#test_directory_structure:
#    resource: "@TestDirectoryStructureBundle/Resources/config/routing.yml"
#    prefix:   /

#angry_chimps_security:
#    resource: "@AngryChimpsSecurityBundle/Resources/config/routing.yml"
#    prefix:   /

angry_chimps_api:
    resource: "@AngryChimpsApiBundle/Resources/config/routing.yml"
    prefix:   /api/v1

ac_norm:
    resource: "@ACNormBundle/Resources/config/routing.yml"
    prefix:   /norm

angry_chimps_ac:
    resource: "@AngryChimpsAcBundle/Resources/config/routing.yml"
    prefix:   /

##From FOS Facebook Bundle
#_security_check:
#    pattern:  /login_check
#_security_logout:
#    pattern:  /logout
