angry_chimps_task:
    resource: "@AngryChimpsTaskBundle/Resources/config/routing.yml"
    prefix:   /task

angry_chimps_media:
    resource: "@AngryChimpsMediaBundle/Resources/config/routing.yml"
    prefix:   /media

angry_chimps_sample:
    resource: "@AngryChimpsSampleBundle/Resources/config/routing.yml"
    prefix:   /sample

angry_chimps_elasticsearch:
    resource: "@AngryChimpsElasticsearchBundle/Resources/config/routing.yml"
    prefix:   /

angry_chimps_guzzle:
    resource: "@AngryChimpsGuzzleBundle/Resources/config/routing.yml"
    prefix:   /

angry_chimps_geo:
    resource: "@AngryChimpsGeoBundle/Resources/config/routing.yml"
    prefix:   /

angry_chimps_mailer:
    resource: "@AngryChimpsMailerBundle/Resources/config/routing.yml"
    prefix:   /

angry_chimps_admin:
    resource: "@AngryChimpsAdminBundle/Resources/config/routing.yml"
    prefix:   /admin

#test_directory_structure:
#    resource: "@TestDirectoryStructureBundle/Resources/config/routing.yml"
#    prefix:   /

#angry_chimps_security:
#    resource: "@AngryChimpsSecurityBundle/Resources/config/routing.yml"
#    prefix:   /

angry_chimps_api:
    resource: "@AngryChimpsApiBundle/Resources/config/routing.yml"
    prefix:   /api/v1

ac_norm:
    resource: "@ACNormBundle/Resources/config/routing.yml"
    prefix:   /norm

angry_chimps_ac:
    resource: "@AngryChimpsAcBundle/Resources/config/routing.yml"
    prefix:   /

##From FOS Facebook Bundle
#_security_check:
#    pattern:  /login_check
#_security_logout:
#    pattern:  /logout
