security:
    providers:
        in_memory:
            memory: ~
        ac:
          id: ac_user_provider
    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        default:
            anonymous: ~
    encoders:
        Norm\riak\Member: bcrypt