services:
#    angry_chimps_guzzle.example:
#        class: AngryChimps\GuzzleBundle\Example
#        arguments: [@service_id, "plain_value", %parameter%]
    angry_chimps_guzzle.guzzle:
        class: AngryChimps\GuzzleBundle\Services\GuzzleService
        arguments: ["@logger"]
