angry_chimps_admin_homepage:
    path:     /hello/{name}
    defaults: { _controller: AngryChimpsAdminBundle:Default:index }
angry_chimps_admin_riak_query:
    path:     /riak
    methods: ["GET", "POST"]
    defaults: { _controller: angry_chimps_admin.riak.controller:indexAction }
