id: default
name: default
description: This is one of the best vets you will find
is_mobile: false
mobile_radius_miles: null
services:
  - 100
  - 200
animals:
  - 1000
  - 2000
address:
  street1: '720 Valencia St'
  street2:
  zip: 94110
  phone: 415.552.1969
hours:
  sunday:
    start: null,
    end: null,
  monday:
    start: "09:00:00-0800"
    end: "17:00:00-0800"
  tuesday:
    start: "09:00:00-0800"
    end: "17:00:00-0800"
  wednesday:
    start: "09:00:00-0800"
    end: "17:00:00-0800"
  thursday:
    start: "09:00:00-0800"
    end: "17:00:00-0800"
  friday:
    start: "09:00:00-0800"
    end: "17:00:00-0800"
  saturday:
    start: null,
    end: null,
