parameters:
#    angry_chimps_ac.example.class: AngryChimps\AcBundle\Example

services:
#    angry_chimps_ac.example:
#        class: %angry_chimps_ac.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
