services:
#    angry_chimps_geo.example:
#        class: AngryChimps\GeoBundle\Example
#        arguments: [@service_id, "plain_value", %parameter%]
    angry_chimps_geo.geolocation:
        class: AngryChimps\GeoBundle\Services\GeolocationService
        arguments: ["@angry_chimps_guzzle.guzzle"]
