angry_chimps_api_session:
    path:     /session
    methods: ["GET"]
    defaults: { _controller: angry_chimps_api.session.controller:indexGetAction }
angry_chimps_api_member_get:
    path:     /member/{id}
    methods: ["GET"]
    defaults: { _controller: angry_chimps_api.member.controller:indexGetAction }
angry_chimps_api_member_put:
    path:     /member/{id}
    methods: ["PUT"]
    defaults: { _controller: angry_chimps_api.member.controller:indexPutAction }
angry_chimps_api_member_delete:
    path:     /member/{id}
    methods: ["DELETE"]
    defaults: { _controller: angry_chimps_api.member.controller:indexDeleteAction }
angry_chimps_api_auth_login:
    path:     /auth/login
    methods: ["POST"]
    defaults: { _controller: angry_chimps_api.auth.controller:loginAction }
angry_chimps_api_auth_register:
    path:     /auth/register
    methods: ["POST"]
    defaults: { _controller: angry_chimps_api.auth.controller:registerAction }
angry_chimps_api_company_get:
    path:     /company/{id}
    methods: ["GET"]
    defaults: { _controller: angry_chimps_api.company.controller:indexGetAction }
angry_chimps_api_company_post:
    path:     /company
    methods: ["POST"]
    defaults: { _controller: angry_chimps_api.company.controller:indexPostAction }
angry_chimps_api_company_put:
    path:     /company/{id}
    methods: ["PUT"]
    defaults: { _controller: angry_chimps_api.company.controller:indexPutAction }
angry_chimps_api_company_delete:
    path:     /company/{id}
    methods: ["DELETE"]
    defaults: { _controller: angry_chimps_api.company.controller:indexDeleteAction }
angry_chimps_api_location_get:
    path:     /location/{id}
    methods: ["GET"]
    defaults: { _controller: angry_chimps_api.location.controller:indexGetAction }
angry_chimps_api_location_post:
    path:     /location
    methods: ["POST"]
    defaults: { _controller: angry_chimps_api.location.controller:indexPostAction }
angry_chimps_api_location_put:
    path:     /location/{id}
    methods: ["PUT"]
    defaults: { _controller: angry_chimps_api.location.controller:indexPutAction }
angry_chimps_api_location_delete:
    path:     /location/{id}
    methods: ["DELETE"]
    defaults: { _controller: angry_chimps_api.location.controller:indexDeleteAction }

api:
    resource: "@AngryChimpsApiBundle/Controller"
    type:     annotation