#animal
angry_chimps_api_animal_get:
    path:     /animal
    methods: ["GET"]
    defaults: { _controller: angry_chimps_api.animal.controller:indexGetAction }

#service
angry_chimps_api_service_get:
    path:     /service
    methods: ["GET"]
    defaults: { _controller: angry_chimps_api.service.controller:indexGetAction }

#member_media
angry_chimps_api_media_post:
    path:     /media
    methods: ["POST"]
    defaults: { _controller: angry_chimps_api.media.controller:indexPostAction }
angry_chimps_api_media_get:
    path:     /media/{filename}
    methods: ["GET"]
    defaults: { _controller: angry_chimps_api.media.controller:indexGetAction }

#session
angry_chimps_api_session_get:
    path:     /session/{id}
    methods: ["GET"]
    defaults: { _controller: angry_chimps_api.session.controller:indexGetAction }
angry_chimps_api_session_post:
    path:     /session
    methods: ["POST"]
    defaults: { _controller: angry_chimps_api.session.controller:indexPostAction }

#member
angry_chimps_api_member_get:
    path:     /member/{id}
    methods: ["GET"]
    defaults: { _controller: angry_chimps_api.member.controller:indexGetAction }
angry_chimps_api_member_post:
    path:     /member
    methods: ["POST"]
    defaults: { _controller: angry_chimps_api.member.controller:indexPostAction }
angry_chimps_api_member_patch:
    path:     /member/{id}
    methods: ["PATCH"]
    defaults: { _controller: angry_chimps_api.member.controller:indexPatchAction }
angry_chimps_api_member_delete:
    path:     /member/{id}
    methods: ["DELETE"]
    defaults: { _controller: angry_chimps_api.member.controller:indexDeleteAction }

#auth
angry_chimps_api_auth_login:
    path:     /auth/login
    methods: ["POST"]
    defaults: { _controller: angry_chimps_api.auth.controller:loginAction }
angry_chimps_api_auth_register:
    path:     /auth/register
    methods: ["POST"]
    defaults: { _controller: angry_chimps_api.auth.controller:registerAction }

#company
angry_chimps_api_company_get:
    path:     /company/{id}
    methods: ["GET"]
    defaults: { _controller: angry_chimps_api.company.controller:indexGetAction }
angry_chimps_api_company_post:
    path:     /company
    methods: ["POST"]
    defaults: { _controller: angry_chimps_api.company.controller:indexPostAction }
angry_chimps_api_company_patch:
    path:     /company/{id}
    methods: ["PATCH"]
    defaults: { _controller: angry_chimps_api.company.controller:indexPatchAction }
angry_chimps_api_company_delete:
    path:     /company/{id}
    methods: ["DELETE"]
    defaults: { _controller: angry_chimps_api.company.controller:indexDeleteAction }

#location
angry_chimps_api_location_get:
    path:     /location/{id}
    methods: ["GET"]
    defaults: { _controller: angry_chimps_api.location.controller:indexGetAction }
angry_chimps_api_location_post:
    path:     /location
    methods: ["POST"]
    defaults: { _controller: angry_chimps_api.location.controller:indexPostAction }
angry_chimps_api_location_patch:
    path:     /location/{id}
    methods: ["PATCH"]
    defaults: { _controller: angry_chimps_api.location.controller:indexPatchAction }
angry_chimps_api_location_delete:
    path:     /location/{id}
    methods: ["DELETE"]
    defaults: { _controller: angry_chimps_api.location.controller:indexDeleteAction }

#staff
angry_chimps_api_staff_get:
    path:     /staff/{id}
    methods: ["GET"]
    defaults: { _controller: angry_chimps_api.staff.controller:indexGetAction }
angry_chimps_api_staff_get_multiple:
    path:     /staff
    methods: ["GET"]
    defaults: { _controller: angry_chimps_api.staff.controller:indexGetMultipleAction }
angry_chimps_api_staff_post:
    path:     /staff
    methods: ["POST"]
    defaults: { _controller: angry_chimps_api.staff.controller:indexPostAction }
angry_chimps_api_staff_patch:
    path:     /staff/{id}
    methods: ["PATCH"]
    defaults: { _controller: angry_chimps_api.staff.controller:indexPatchAction }
angry_chimps_api_staff_delete:
    path:     /staff/{id}
    methods: ["DELETE"]
    defaults: { _controller: angry_chimps_api.staff.controller:indexDeleteAction }

#review
angry_chimps_api_review_get:
    path:     /review/{id}
    methods: ["GET"]
    defaults: { _controller: angry_chimps_api.review.controller:indexGetAction }
angry_chimps_api_review_get_multiple:
    path:     /review
    methods: ["GET"]
    defaults: { _controller: angry_chimps_api.review.controller:indexGetMultipleAction }
angry_chimps_api_review_post:
    path:     /review
    methods: ["POST"]
    defaults: { _controller: angry_chimps_api.review.controller:indexPostAction }
angry_chimps_api_review_patch:
    path:     /review/{id}
    methods: ["PATCH"]
    defaults: { _controller: angry_chimps_api.review.controller:indexPatchAction }
angry_chimps_api_review_delete:
    path:     /review/{id}
    methods: ["DELETE"]
    defaults: { _controller: angry_chimps_api.review.controller:indexDeleteAction }

#service
angry_chimps_api_service_get:
    path:     /service/{id}
    methods: ["GET"]
    defaults: { _controller: angry_chimps_api.service.controller:indexGetAction }
angry_chimps_api_service_post:
    path:     /service
    methods: ["POST"]
    defaults: { _controller: angry_chimps_api.service.controller:indexPostAction }
angry_chimps_api_service_patch:
    path:     /service/{id}
    methods: ["PATCH"]
    defaults: { _controller: angry_chimps_api.service.controller:indexPatchAction }
angry_chimps_api_service_delete:
    path:     /service/{id}
    methods: ["DELETE"]
    defaults: { _controller: angry_chimps_api.service.controller:indexDeleteAction }

#categories
angry_chimps_api_categories_get:
    path:     /categories
    methods: ["GET"]
    defaults: { _controller: angry_chimps_api.categories.controller:indexGetAction }

#signup
angry_chimps_api_signup_registerProviderAd:
    path:     /signup/registerProviderAd
    methods: ["POST"]
    defaults: { _controller: angry_chimps_api.signup.controller:registerProviderAdAction }
angry_chimps_api_signup_registerProviderCompany:
    path:     /signup/registerProviderCompany
    methods: ["POST"]
    defaults: { _controller: angry_chimps_api.signup.controller:registerProviderCompanyAction }
angry_chimps_api_signup_uploadFirstAdPhoto:
    path:     /signup/uploadFirstAdPhoto
    methods: ["POST"]
    defaults: { _controller: angry_chimps_api.signup.controller:uploadFirstAdPhotoAction }

#search
angry_chimps_api_search_post:
    path:     /search
    methods: ["POST"]
    defaults: { _controller: angry_chimps_api.search.controller:indexPostAction }

#company_media
angry_chimps_api_company_media_post:
    path:     /companyMedia/{companyId}/{providerAdId}
    methods: ["POST"]
    defaults: { _controller: angry_chimps_api.company_media.controller:indexPostAction , providerAdId: false}

#member_media
angry_chimps_api_member_media_post:
    path:     /memberMedia/{memberId}
    methods: ["POST"]
    defaults: { _controller: angry_chimps_api.member_media.controller:indexPostAction }

#availability
angry_chimps_api_availability_post:
    path:     /availability
    methods: ["POST"]
    defaults: { _controller: angry_chimps_api.availability.controller:indexPostAction}
angry_chimps_api_availability_delete:
    path:     /availability
    methods: ["DELETE"]
    defaults: { _controller: angry_chimps_api.availability.controller:indexDeleteAction}

#provider_ad_immutable
angry_chimps_api_provider_ad_immutable_post:
    path:     /providerAdImmutable/{providerAdImmutableId}
    methods: ["GET"]
    defaults: { _controller: angry_chimps_api.provider_ad_immutable.controller:indexGetAction}

#calendar
angry_chimps_api_calendar_get:
    path:     /calendar/{calendarId}/{serviceId}
    methods: ["GET"]
    defaults: { _controller: angry_chimps_api.calendar.controller:indexGetAction, serviceId: null}
angry_chimps_api_calendar_post:
    path:     /calendar
    methods: ["POST"]
    defaults: { _controller: angry_chimps_api.calendar.controller:indexPostAction}
angry_chimps_api_calendar_patch:
    path:     /calendar/{calendarId}
    methods: ["PATCH"]
    defaults: { _controller: angry_chimps_api.calendar.controller:indexPatchAction}
angry_chimps_api_calendar_delete:
    path:     /calendar/{calendarId}
    methods: ["DELETE"]
    defaults: { _controller: angry_chimps_api.calendar.controller:indexDeleteAction}

#booking
angry_chimps_api_booking_get:
    path:     /booking/{bookingId}
    methods: ["GET"]
    defaults: { _controller: angry_chimps_api.booking.controller:indexGetAction}
angry_chimps_api_booking_post:
    path:     /booking
    methods: ["POST"]
    defaults: { _controller: angry_chimps_api.booking.controller:indexPostAction}
angry_chimps_api_booking_delete:
    path:     /booking/{bookingId}
    methods: ["DELETE"]
    defaults: { _controller: angry_chimps_api.booking.controller:indexDeleteAction}

#comment
angry_chimps_api_comment_get:
    path:     /comment/{companyId}
    methods: ["GET"]
    defaults: { _controller: angry_chimps_api.comment.controller:indexGetAction}
angry_chimps_api_comment_post:
    path:     /comment
    methods: ["POST"]
    defaults: { _controller: angry_chimps_api.comment.controller:indexPostAction}

#api:
#    resource: "@AngryChimpsApiBundle/Controller"
#    type:     annotation

#test
angry_chimps_api_test_run:
    path:     /test/run/{methodName}
    methods: ["GET"]
    defaults: { _controller: angry_chimps_api.test.controller:runAction}
angry_chimps_api_test_env:
    path:     /test/env
    methods: ["GET"]
    defaults: { _controller: angry_chimps_api.test.controller:envAction}
angry_chimps_api_test_create:
    path:     /test/create
    methods: ["GET"]
    defaults: { _controller: angry_chimps_api.test.controller:createAction}
angry_chimps_api_test_retrieve:
    path:     /test/retrieve/{id}
    methods: ["GET"]
    defaults: { _controller: angry_chimps_api.test.controller:retrieveAction}
