#session
angry_chimps_api_session:
    path:     /session
    methods: ["GET"]
    defaults: { _controller: angry_chimps_api.session.controller:indexGetAction }

#member
angry_chimps_api_member_get:
    path:     /member/{id}
    methods: ["GET"]
    defaults: { _controller: angry_chimps_api.member.controller:indexGetAction }
angry_chimps_api_member_put:
    path:     /member/{id}
    methods: ["PUT"]
    defaults: { _controller: angry_chimps_api.member.controller:indexPutAction }
angry_chimps_api_member_delete:
    path:     /member/{id}
    methods: ["DELETE"]
    defaults: { _controller: angry_chimps_api.member.controller:indexDeleteAction }

#auth
angry_chimps_api_auth_login:
    path:     /auth/login
    methods: ["POST"]
    defaults: { _controller: angry_chimps_api.auth.controller:loginAction }
angry_chimps_api_auth_register:
    path:     /auth/register
    methods: ["POST"]
    defaults: { _controller: angry_chimps_api.auth.controller:registerAction }

#company
angry_chimps_api_company_get:
    path:     /company/{id}
    methods: ["GET"]
    defaults: { _controller: angry_chimps_api.company.controller:indexGetAction }
angry_chimps_api_company_post:
    path:     /company
    methods: ["POST"]
    defaults: { _controller: angry_chimps_api.company.controller:indexPostAction }
angry_chimps_api_company_put:
    path:     /company/{id}
    methods: ["PUT"]
    defaults: { _controller: angry_chimps_api.company.controller:indexPutAction }
angry_chimps_api_company_delete:
    path:     /company/{id}
    methods: ["DELETE"]
    defaults: { _controller: angry_chimps_api.company.controller:indexDeleteAction }

#location
angry_chimps_api_location_get:
    path:     /location/{id}
    methods: ["GET"]
    defaults: { _controller: angry_chimps_api.location.controller:indexGetAction }
angry_chimps_api_location_post:
    path:     /location
    methods: ["POST"]
    defaults: { _controller: angry_chimps_api.location.controller:indexPostAction }
angry_chimps_api_location_put:
    path:     /location/{id}
    methods: ["PUT"]
    defaults: { _controller: angry_chimps_api.location.controller:indexPutAction }
angry_chimps_api_location_delete:
    path:     /location/{id}
    methods: ["DELETE"]
    defaults: { _controller: angry_chimps_api.location.controller:indexDeleteAction }

#service
angry_chimps_api_service_get:
    path:     /service/{id}
    methods: ["GET"]
    defaults: { _controller: angry_chimps_api.service.controller:indexGetAction }
angry_chimps_api_service_post:
    path:     /service
    methods: ["POST"]
    defaults: { _controller: angry_chimps_api.service.controller:indexPostAction }
angry_chimps_api_service_put:
    path:     /service/{id}
    methods: ["PUT"]
    defaults: { _controller: angry_chimps_api.service.controller:indexPutAction }
angry_chimps_api_service_delete:
    path:     /service/{id}
    methods: ["DELETE"]
    defaults: { _controller: angry_chimps_api.service.controller:indexDeleteAction }

#categories
angry_chimps_api_categories_get:
    path:     /categories
    methods: ["GET"]
    defaults: { _controller: angry_chimps_api.categories.controller:indexGetAction }

#signup
angry_chimps_api_signup_registerProviderAd:
    path:     /signup/registerProviderAd
    methods: ["POST"]
    defaults: { _controller: angry_chimps_api.signup.controller:registerProviderAdAction }
angry_chimps_api_signup_registerProviderCompany:
    path:     /signup/registerProviderCompany
    methods: ["POST"]
    defaults: { _controller: angry_chimps_api.signup.controller:registerProviderCompanyAction }
angry_chimps_api_signup_uploadFirstAdPhoto:
    path:     /signup/uploadFirstAdPhoto
    methods: ["POST"]
    defaults: { _controller: angry_chimps_api.signup.controller:uploadFirstAdPhotoAction }

#search
angry_chimps_api_search_post:
    path:     /search
    methods: ["POST"]
    defaults: { _controller: angry_chimps_api.search.controller:indexPostAction }

#api:
#    resource: "@AngryChimpsApiBundle/Controller"
#    type:     annotation