parameters:
    angry_chimps_api.auth.class: AngryChimps\ApiBundle\Services\AuthService
    angry_chimps_api.member.class: AngryChimps\ApiBundle\Services\MemberService
    angry_chimps_api.company.class: AngryChimps\ApiBundle\Services\CompanyService
    angry_chimps_api.location.class: AngryChimps\ApiBundle\Services\LocationService
    angry_chimps_api.service.class: AngryChimps\ApiBundle\Services\ServiceService
    angry_chimps_api.response.class: AngryChimps\ApiBundle\Services\ResponseService
    angry_chimps_api.session.class: AngryChimps\ApiBundle\Services\SessionService
    angry_chimps_api.categories.class: AngryChimps\ApiBundle\Services\CategoriesService
    angry_chimps_api.signup.class: AngryChimps\ApiBundle\Services\SignupService
    angry_chimps_api.provider_ad.class: AngryChimps\ApiBundle\Services\ProviderAdService
    angry_chimps_api.calendar.class: AngryChimps\ApiBundle\Services\CalendarService
    angry_chimps_api.search.class: AngryChimps\ApiBundle\Services\SearchService
    angry_chimps_api.company_media.class: AngryChimps\ApiBundle\Services\CompanyMediaService
    angry_chimps_api.provider_ad_immutable.class: AngryChimps\ApiBundle\Services\ProviderAdImmutableService

    angry_chimps_api.controller.session.class: AngryChimps\ApiBundle\Controller\SessionController
    angry_chimps_api.controller.member.class: AngryChimps\ApiBundle\Controller\MemberController
    angry_chimps_api.controller.auth.class: AngryChimps\ApiBundle\Controller\AuthController
    angry_chimps_api.controller.company.class: AngryChimps\ApiBundle\Controller\CompanyController
    angry_chimps_api.controller.location.class: AngryChimps\ApiBundle\Controller\LocationController
    angry_chimps_api.controller.service.class: AngryChimps\ApiBundle\Controller\ServiceController
    angry_chimps_api.controller.categories.class: AngryChimps\ApiBundle\Controller\CategoriesController
    angry_chimps_api.controller.signup.class: AngryChimps\ApiBundle\Controller\SignupController
    angry_chimps_api.controller.search.class: AngryChimps\ApiBundle\Controller\SearchController
    angry_chimps_api.controller.company_media.class: AngryChimps\ApiBundle\Controller\CompanyMediaController
    angry_chimps_api.controller.provider_ad_immutable.class: AngryChimps\ApiBundle\Controller\ProviderAdImmutableController
    angry_chimps_api.controller.availability.class: AngryChimps\ApiBundle\Controller\AvailabilityController

services:

##############################################################
###                  Services                              ###
##############################################################
    angry_chimps_api.auth:
        class: "%angry_chimps_api.auth.class%"
        arguments: ["@angry_chimps_mailer.mailer", "@templating", "@validator", "@angry_chimps_api.member"]
    angry_chimps_api.member:
        class: "%angry_chimps_api.member.class%"
        arguments:
            - "@angry_chimps_mailer.mailer"
            - "@templating"
            - "@validator"
            - "@ac_norm.norm.riak"
            - "@ac_norm.norm.mysql"
            - "@angry_chimps_task.tasker"
    angry_chimps_api.company:
        class: "%angry_chimps_api.company.class%"
        arguments: ["@validator", "@ac_norm.norm.riak", "@ac_norm.norm.mysql"]
    angry_chimps_api.location:
        class: "%angry_chimps_api.location.class%"
        arguments: ["@validator", "@angry_chimps_geo.geolocation", "@ac_norm.norm.riak", "@ac_norm.norm.mysql"]
    angry_chimps_api.service:
        class: "%angry_chimps_api.service.class%"
        arguments: ["@validator", "@ac_norm.norm.riak", "@ac_norm.norm.mysql"]
    angry_chimps_api.response:
        class: "%angry_chimps_api.response.class%"
        arguments: ["@request_stack", "@logger", "@fos_rest.view_handler"]
#    angry_chimps_api.guzzle:
#        class: AngryChimps\ApiBundle\Services\GuzzleService
#        tags:
#            -  { name: guzzle.client }
    angry_chimps_api.session:
        class: "%angry_chimps_api.session.class%"
        arguments: ["@request_stack", "%angry_chimps_api.session_header_name%", "@ac_norm.norm.riak", "@ac_norm.norm.mysql"]
    angry_chimps_api.categories:
        class: "%angry_chimps_api.categories.class%"
    angry_chimps_api.signup:
        class: "%angry_chimps_api.signup.class%"
        arguments:
            - "@angry_chimps_api.member"
            - "@angry_chimps_api.company"
            - "@angry_chimps_api.location"
            - "@angry_chimps_api.provider_ad"
            - "@angry_chimps_api.calendar"
            - "@angry_chimps_api.service"
            - "@angry_chimps_api.auth"
            - "@validator"
            - "@angry_chimps_api.session"
            - "@ac_norm.norm.riak"
            - "@ac_norm.norm.mysql"
            - "@angry_chimps_media.media"
            - "@angry_chimps_geo.time"
    angry_chimps_api.provider_ad:
        class: "%angry_chimps_api.provider_ad.class%"
        arguments:
            - "@validator"
            - "@ac_norm.norm.riak"
            - "@ac_norm.norm.mysql"
            - "@ac_norm.norm.es"
            - "@angry_chimps_api.company"
            - "@angry_chimps_api.location"
            - "@angry_chimps_api.calendar"
            - "@angry_chimps_api.service"
    angry_chimps_api.calendar:
        class: "%angry_chimps_api.calendar.class%"
        arguments: ["@ac_norm.norm.riak", "@ac_norm.norm.mysql"]
    angry_chimps_api.search:
        class: "%angry_chimps_api.search.class%"
        arguments: ["@ac_norm.norm.es"]
    angry_chimps_api.company_media:
        class: "%angry_chimps_api.company_media.class%"
        arguments:
            - "@angry_chimps_media.media"
            - "@ac_norm.norm.riak"
    angry_chimps_api.provider_ad_immutable:
        class: "%angry_chimps_api.provider_ad_immutable.class%"
        arguments:
            - "@ac_norm.norm.riak"

##############################################################
###                  Controllers                           ###
##############################################################
    angry_chimps_api.session.controller:
            class:     "%angry_chimps_api.controller.session.class%"
            arguments: ["@request_stack", "@angry_chimps_api.session", "@angry_chimps_api.response"]

    angry_chimps_api.member.controller:
            class:     "%angry_chimps_api.controller.member.class%"
            arguments: ["@request_stack", "@angry_chimps_api.session", "@angry_chimps_api.response", "@angry_chimps_api.member", "@angry_chimps_api.auth"]

    angry_chimps_api.auth.controller:
            class:     "%angry_chimps_api.controller.auth.class%"
            arguments: ["@request_stack", "@angry_chimps_api.session", "@angry_chimps_api.response", "@angry_chimps_api.auth", "%kernel.debug%", "@angry_chimps_api.member"]

    angry_chimps_api.company.controller:
            class:     "%angry_chimps_api.controller.company.class%"
            arguments: ["@request_stack", "@angry_chimps_api.session", "@angry_chimps_api.response", "@angry_chimps_api.company"]

    angry_chimps_api.location.controller:
            class:     "%angry_chimps_api.controller.location.class%"
            arguments: ["@request_stack", "@angry_chimps_api.session", "@angry_chimps_api.response", "@angry_chimps_api.location", "@angry_chimps_api.company"]

    angry_chimps_api.service.controller:
            class:     "%angry_chimps_api.controller.service.class%"
            arguments: ["@request_stack", "@angry_chimps_api.session", "@angry_chimps_api.response", "@angry_chimps_api.service", "@angry_chimps_api.company"]

    angry_chimps_api.categories.controller:
            class:     "%angry_chimps_api.controller.categories.class%"
            arguments: ["@request_stack", "@angry_chimps_api.session", "@angry_chimps_api.response", "@angry_chimps_api.categories"]

    angry_chimps_api.signup.controller:
            class:     "%angry_chimps_api.controller.signup.class%"
            arguments:
                - "@request_stack"
                - "@angry_chimps_api.session"
                - "@angry_chimps_api.response"
                - "@angry_chimps_api.signup"
                - "@angry_chimps_geo.geolocation"
                - "@angry_chimps_api.provider_ad"
                - "@angry_chimps_api.company"
                - "@angry_chimps_api.location"

    angry_chimps_api.search.controller:
            class:     "%angry_chimps_api.controller.search.class%"
            arguments: ["@request_stack", "@angry_chimps_api.session", "@angry_chimps_api.response", "@angry_chimps_api.search"]

    angry_chimps_api.company_media.controller:
            class:     "%angry_chimps_api.controller.company_media.class%"
            arguments:
                - "@request_stack"
                - "@angry_chimps_api.session"
                - "@angry_chimps_api.response"
                - "@angry_chimps_api.company"
                - "@angry_chimps_api.company_media"
                - "@angry_chimps_api.provider_ad"

    angry_chimps_api.provider_ad_immutable.controller:
            class:     "%angry_chimps_api.controller.provider_ad_immutable.class%"
            arguments:
                - "@request_stack"
                - "@angry_chimps_api.session"
                - "@angry_chimps_api.response"
                - "@angry_chimps_api.provider_ad_immutable"

    angry_chimps_api.availability.controller:
            class:     "%angry_chimps_api.controller.availability.class%"
            arguments:
                - "@request_stack"
                - "@angry_chimps_api.session"
                - "@angry_chimps_api.response"
                - "@angry_chimps_api.calendar"


##############################################################
###                  Listeners                             ###
##############################################################
    kernel.listener.angry_chimps_api_exception_listener:
        class: AngryChimps\ApiBundle\EventListener\ExceptionListener
        arguments: ["@angry_chimps_api.response", "%angry_chimps_api.debug%"]
        tags:
            - { name: kernel.event_listener, event: kernel.exception, method: onKernelException }



