parameters:
    angry_chimps_api.controller.session.class: AngryChimps\ApiBundle\Controller\SessionController
    angry_chimps_api.controller.member.class: AngryChimps\ApiBundle\Controller\MemberController
    angry_chimps_api.controller.auth.class: AngryChimps\ApiBundle\Controller\AuthController
    angry_chimps_api.controller.company.class: AngryChimps\ApiBundle\Controller\CompanyController
    angry_chimps_api.controller.location.class: AngryChimps\ApiBundle\Controller\LocationController
    angry_chimps_api.controller.service.class: AngryChimps\ApiBundle\Controller\ServiceController
    angry_chimps_api.controller.categories.class: AngryChimps\ApiBundle\Controller\CategoriesController
    angry_chimps_api.controller.signup.class: AngryChimps\ApiBundle\Controller\SignupController

services:

##############################################################
###                  Services                              ###
##############################################################
    angry_chimps_api.auth:
        class: AngryChimps\ApiBundle\Services\AuthService
        arguments: ["@angry_chimps_mailer.mailer", "@templating", "@validator"]
    angry_chimps_api.member:
        class: AngryChimps\ApiBundle\Services\MemberService
        arguments: ["@angry_chimps_mailer.mailer", "@templating", "@angry_chimps_api.auth", "@validator"]
    angry_chimps_api.company:
        class: AngryChimps\ApiBundle\Services\CompanyService
        arguments: ["@validator"]
    angry_chimps_api.location:
        class: AngryChimps\ApiBundle\Services\LocationService
        arguments: ["@validator", "@angry_chimps_geo.geolocation"]
    angry_chimps_api.service:
        class: AngryChimps\ApiBundle\Services\ServiceService
        arguments: ["@validator"]
    angry_chimps_api.response:
        class: AngryChimps\ApiBundle\Services\ResponseService
        arguments: ["@request_stack", "@logger", "@fos_rest.view_handler"]
#    angry_chimps_api.guzzle:
#        class: AngryChimps\ApiBundle\Services\GuzzleService
#        tags:
#            -  { name: guzzle.client }
    angry_chimps_api.session:
        class: AngryChimps\ApiBundle\Services\SessionService
        arguments: ["@request_stack", "%angry_chimps_api.session_header_name%"]
    angry_chimps_api.categories:
        class: AngryChimps\ApiBundle\Services\CategoriesService
    angry_chimps_api.signup:
        class: AngryChimps\ApiBundle\Services\SignupService
        arguments:
            - "@angry_chimps_api.member"
            - "@angry_chimps_api.company"
            - "@angry_chimps_api.location"
            - "@angry_chimps_api.provider_ad"
            - "@angry_chimps_api.calendar"
            - "@angry_chimps_api.service"
            - "@angry_chimps_api.auth"
            - "@validator"
            - "@angry_chimps_api.session"
    angry_chimps_api.provider_ad:
        class: AngryChimps\ApiBundle\Services\ProviderAdService
        arguments: ["@validator"]
    angry_chimps_api.calendar:
        class: AngryChimps\ApiBundle\Services\CalendarService

##############################################################
###                  Controllers                           ###
##############################################################
    angry_chimps_api.session.controller:
            class:     "%angry_chimps_api.controller.session.class%"
            arguments: ["@request_stack", "@angry_chimps_api.session", "@angry_chimps_api.response"]

    angry_chimps_api.member.controller:
            class:     "%angry_chimps_api.controller.member.class%"
            arguments: ["@request_stack", "@angry_chimps_api.session", "@angry_chimps_api.response", "@angry_chimps_api.member", "@angry_chimps_api.auth"]

    angry_chimps_api.auth.controller:
            class:     "%angry_chimps_api.controller.auth.class%"
            arguments: ["@request_stack", "@angry_chimps_api.session", "@angry_chimps_api.response", "@angry_chimps_api.auth", "%kernel.debug%"]

    angry_chimps_api.company.controller:
            class:     "%angry_chimps_api.controller.company.class%"
            arguments: ["@request_stack", "@angry_chimps_api.session", "@angry_chimps_api.response", "@angry_chimps_api.company"]

    angry_chimps_api.location.controller:
            class:     "%angry_chimps_api.controller.location.class%"
            arguments: ["@request_stack", "@angry_chimps_api.session", "@angry_chimps_api.response", "@angry_chimps_api.location"]

    angry_chimps_api.service.controller:
            class:     "%angry_chimps_api.controller.service.class%"
            arguments: ["@request_stack", "@angry_chimps_api.session", "@angry_chimps_api.response", "@angry_chimps_api.service"]

    angry_chimps_api.categories.controller:
            class:     "%angry_chimps_api.controller.categories.class%"
            arguments: ["@request_stack", "@angry_chimps_api.session", "@angry_chimps_api.response", "@angry_chimps_api.categories"]

    angry_chimps_api.signup.controller:
            class:     "%angry_chimps_api.controller.signup.class%"
            arguments: ["@request_stack", "@angry_chimps_api.session", "@angry_chimps_api.response", "@angry_chimps_api.signup", "@angry_chimps_geo.geolocation"]


##############################################################
###                  Listeners                             ###
##############################################################
    kernel.listener.angry_chimps_api_exception_listener:
        class: AngryChimps\ApiBundle\EventListener\ExceptionListener
        arguments: ["@angry_chimps_api.response", "%angry_chimps_api.debug%"]
        tags:
            - { name: kernel.event_listener, event: kernel.exception, method: onKernelException }
