services:
#    angry_chimps_api.example:
#        class: AngryChimps\ApiBundle\Example
#        arguments: [@service_id, "plain_value", %parameter%]

    angry_chimps_api.auth:
        class: AngryChimps\ApiBundle\Services\AuthService
        arguments: ["@armetiz.facebook","@angry_chimps_mailer.mailer", "@templating"]
    angry_chimps_api.member:
        class: AngryChimps\ApiBundle\Services\MemberService
        arguments: ["@angry_chimps_mailer.mailer", "@templating", "@angry_chimps_api.auth", "@validator"]
